# Docker compose file

services:
  transmission:
    build: .
    environment:
      - NETWORK_RANGE=10.*,*
      - USERNAME=test
      - PASSWORD=test
      - PORT=9091
      - PEERPORT=51413
    volumes:
      - ./config:/config
      - ./complete:/complete
      - ./incomplete:/incomplete
      - ./watch_folder:/watch_folder
    ports:
      - 8080:9091/tcp
